### ISSUE TITLE
Test coverage in Code Climate

### ISSUE THREAD

**Issue by yous** [jackdcrawford/five#121]
With Travis CI and Code Climate, we can use [Code Climate's JavaScript reporter library](https://www.npmjs.org/package/codeclimate-test-reporter). There is some instruction for [JavaScript](http://docs.travis-ci.com/user/code-climate/#JavaScript). For instance using [istanbul library](http://gotwarlost.github.io/istanbul/),

Adding these lines to `.travis.yml` seems to work:

``` yaml
addons:
  code_climate:
    repo_token: aff33f...
before_script:
  - npm install -g istanbul
script:
  - istanbul cover test.js
after_script:
  - cat coverage/lcov.info | codeclimate
```
